version: '3.8'

services:
  # MySQL-Datenbank-Service
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3307:3306"

  # Webserver-Service mit Nginx
  webserver:
    image: nginx:latest
    ports:
      - "8081:80"

  # Deine eigene Anwendung
  myapp:
    build:
      context: .
